// Translation dictionaries
const translations = {
  fi: {
    home: "Etusivu",
    menu: "Ruokalista",
    info: "Tietoa",
    contact: "Yhteystiedot",
    searchPlaceholder: "Etsi ruokia...",
    brand: "TK",
    language: "Kieli:",
    loginTitle: "Kirjaudu sisään",
    namePlaceholder: "Nimi (vain rekisteröinti)",
    emailPlaceholder: "Sähköposti",
    passwordPlaceholder: "Salasana",
    student: "Opiskelija (saat alennuksia)",
    login: "Kirjaudu",
    register: "Rekisteröidy",
    welcome: "Tervetuloa, ",
    adminPanel: "⚙️ Hallintapaneeli",
    logout: "Kirjaudu ulos",
    heroTitle: "Tervetuloa Apricukseen",
    heroSubtitle: "Ainutlaatuisia makuelämyksiä sydämessä kaupunkia",
    exploreMenu: "Tutustu ruokalistaan",
    readMore: "Lue lisää",
    filterFoods: "Suodata ruokia",
    diet: "Ruokavalio",
    vegan: "🌱 Vegaani",
    vegetarian: "🥬 Kasvisruoka",
    glutenFree: "🌾 Gluteeniton",
    loading: "Ladataan...",
    loginAdmin: "Kirjaudu hallintapaneeliin",
    emailLabel: "Sähköposti:",
    passwordLabel: "Salasana:",
    adminLogin: "⚡ Admin-kirjautuminen",
    adminUser: "Admin",
    backToMain: "Takaisin etusivulle",
    dashboard: "Kojelauta",
    menuManagement: "Ruokalistan hallinta",
    orders: "Tilaukset",
    categories: "Kategoriat",
    customers: "Asiakkaat",
    settings: "Asetukset",
    refreshStats: "Päivitä tilastot",
    totalOrders: "Tilauksia yhteensä",
    totalRevenue: "Kokonaistulot",
    totalRecipes: "Ruokalajeja",
    totalUsers: "Rekisteröityneitä käyttäjiä",
    recentOrders: "Viimeisimmät tilaukset",
    addDish: "Lisää uusi ruokalaji",
    searchDish: "Hae ruokalajia...",
    allCategories: "Kaikki kategoriat",
    all: "Kaikki",
    available: "Saatavilla",
    notAvailable: "Ei saatavilla",
    image: "Kuva",
    name: "Nimi",
    category: "Kategoria",
    price: "Hinta",
    availability: "Saatavuus",
    actions: "Toiminnot",
    ordersManagement: "Tilausten hallinta",
    allOrders: "Kaikki tilaukset",
    pending: "Odottaa",
    confirmed: "Vahvistettu",
    preparing: "Valmistetaan",
    ready: "Valmis",
    delivered: "Toimitettu",
    cancelled: "Peruutettu",
    refresh: "Päivitä",
    categoriesManagement: "Kategorioiden hallinta",
    addCategory: "Lisää kategoria",
    customersManagement: "Asiakkaiden hallinta",
    email: "Sähköposti",
    registrationDate: "Rekisteröitymispäivä",
    ordersCount: "Tilausten määrä",
    restaurantInfo: "Ravintolan tiedot",
    restaurantNameLabel: "Ravintolan nimi:",
    restaurantPhoneLabel: "Puhelinnumero:",
    restaurantEmailLabel: "Sähköposti:",
    save: "Tallenna",
    systemSettings: "Järjestelmän asetukset",
    enableNotifications: "Ota käyttöön ilmoitukset",
    autoRefresh: "Automaattinen päivitys",
    addDishTitle: "Lisää uusi ruokalaji",
    recipeNameFiLabel: "Nimi (suomeksi):",
    recipeNameEnLabel: "Nimi (englanniksi):",
    recipeDescriptionLabel: "Kuvaus:",
    recipePriceLabel: "Hinta (€):",
    recipeCategoryLabel: "Kategoria:",
    selectCategory: "Valitse kategoria",
    recipePreparationTimeLabel: "Valmistusaika (min):",
    recipeImageLabel: "Kuvan URL:",
    recipeIngredientsLabel: "Ainesosat (yksi per rivi):",
    cancel: "Peruuta",
    lactoseFree: "Laktoositon",
    allergens: "Allergeenit (poissulje)",
    nuts: "Pähkinät",
    fish: "Kala",
    shellfish: "Äyriäiset",
    eggs: "Kananmunat",
    soy: "Soija",
    priceRange: "Hintaluokka",
    minPrice: "0€",
    maxPrice: "50€",
    applyFilters: "Käytä suodattimet",
    clearFilters: "Tyhjennä",
    todayMenu: "Tämän päivän ruokalista",
    starters: "Alkuruoat",
    mainCourses: "Pääruoat",
    desserts: "Jälkiruoat",
    drinks: "Juomat",
    coldDrinks: "Kylmät juomat",
    hotDrinks: "Kuumat juomat",
    loadingMenu: "Ladataan ruokalistaa...",
    ourStory: "Tarinmme",
    aboutText1: "Apricus on syntynyt rakkaudesta hyvään ruokaan ja lämpimään vieraanvaraisuuteen. Tarjoamme ainutlaatuisia makuelämyksiä sydämessä kaupunkia.",
    aboutText2: "Käytämme vain tuoreimpia, paikallisia raaka-aineita ja perinteisiä reseptejä modernilla twistillä.",
    freshIngredients: "Tuoreet raaka-aineet",
    localIngredients: "Paikalliset ja sesongin mukaiset ainekset",
    experiencedChefs: "Kokeneet kokit",
    professionalTeam: "Ammattitaitoinen keittiötiimi",
    cozyAtmosphere: "Kodikkas tunnelma",
    warmAtmosphere: "Lämmin ja viihtyisä ympäristö",
    cart: "Ostoskori",
    emptyCart: "Ostoskorisi on tyhjä",
    addFromMenu: "Lisää tuotteita ruokalistasta",
    total: "Yhteensä:",
    checkout: "Siirry kassalle",
    favorites: "Suosikit",
    noFavorites: "Ei suosikkeja vielä",
    addFavorites: "Lisää suosikkeja klikkaamalla sydäntä",
    contactInfo: "Yhteystiedot",
    address: "Osoite",
    addressValue: "mellunmäki 22, Helsinki",
    phone: "Puhelin",
    phoneValue: "+358 4056478",
    emailValue: "tk@gmail.com",
    openingHours: "Aukioloajat",
    monFri: "Ma-Pe: 10:00 - 22:00",
    sat: "La: 11:00 - 23:00",
    sun: "Su: 12:00 - 21:00",
    footerBrand: "Apricus",
    footerDesc: "Ainutlaatuisia makuelämyksiä sydämessä kaupunkia",
    footerContact: "Yhteystiedot",
    footerOpeningHours: "Aukioloajat",
    quickAccess: "Pikakäyttö",
    copyright: "© 2025 Apricus. Kaikki oikeudet pidätetään.",
    designed: "Suunniteltu ja toteutettu ❤️:lla",
    showDetails: "Näytä tiedot",
    addToCart: "Lisää koriin",
    close: "Sulje",
    directions: "Reittiohjeet",
    adminMain: "Pääsivu",
    loadingOrders: "Ladataan tilauksia..."
  },
  en: {
    home: "Home",
    menu: "Menu",
    info: "Info",
    contact: "Contact",
    searchPlaceholder: "Search foods...",
    brand: "TK",
    language: "Language:",
    loginTitle: "Sign In",
    namePlaceholder: "Name (registration only)",
    emailPlaceholder: "Email",
    passwordPlaceholder: "Password",
    student: "Student (get discounts)",
    login: "Login",
    register: "Register",
    welcome: "Welcome, ",
    adminPanel: "⚙️ Admin Panel",
    logout: "Logout",
    heroTitle: "Welcome to Apricus",
    heroSubtitle: "Unique taste experiences in the heart of the city",
    exploreMenu: "Explore Menu",
    readMore: "Read More",
    filterFoods: "Filter Foods",
    diet: "Diet",
    vegan: "🌱 Vegan",
    vegetarian: "🥬 Vegetarian",
    glutenFree: "🌾 Gluten-Free",
    loading: "Loading...",
    loginAdmin: "Sign in to admin panel",
    emailLabel: "Email:",
    passwordLabel: "Password:",
    adminLogin: "⚡ Admin Login",
    adminUser: "Admin",
    backToMain: "Back to main page",
    dashboard: "Dashboard",
    menuManagement: "Menu Management",
    orders: "Orders",
    categories: "Categories",
    customers: "Customers",
    settings: "Settings",
    refreshStats: "Refresh Stats",
    totalOrders: "Total Orders",
    totalRevenue: "Total Revenue",
    totalRecipes: "Total Dishes",
    totalUsers: "Registered Users",
    recentOrders: "Recent Orders",
    addDish: "Add New Dish",
    searchDish: "Search dish...",
    allCategories: "All Categories",
    all: "All",
    available: "Available",
    notAvailable: "Not Available",
    image: "Image",
    name: "Name",
    category: "Category",
    price: "Price",
    availability: "Availability",
    actions: "Actions",
    ordersManagement: "Orders Management",
    allOrders: "All Orders",
    pending: "Pending",
    confirmed: "Confirmed",
    preparing: "Preparing",
    ready: "Ready",
    delivered: "Delivered",
    cancelled: "Cancelled",
    refresh: "Refresh",
    categoriesManagement: "Categories Management",
    addCategory: "Add Category",
    customersManagement: "Customers Management",
    email: "Email",
    registrationDate: "Registration Date",
    ordersCount: "Orders Count",
    restaurantInfo: "Restaurant Info",
    restaurantNameLabel: "Restaurant Name:",
    restaurantPhoneLabel: "Phone Number:",
    restaurantEmailLabel: "Email:",
    save: "Save",
    systemSettings: "System Settings",
    enableNotifications: "Enable Notifications",
    autoRefresh: "Auto Refresh",
    addDishTitle: "Add New Dish",
    recipeNameFiLabel: "Name (Finnish):",
    recipeNameEnLabel: "Name (English):",
    recipeDescriptionLabel: "Description:",
    recipePriceLabel: "Price (€):",
    recipeCategoryLabel: "Category:",
    selectCategory: "Select Category",
    recipePreparationTimeLabel: "Preparation Time (min):",
    recipeImageLabel: "Image URL:",
    recipeIngredientsLabel: "Ingredients (one per line):",
    cancel: "Cancel",
    lactoseFree: "Lactose-Free",
    allergens: "Allergens (exclude)",
    nuts: "Nuts",
    fish: "Fish",
    shellfish: "Shellfish",
    eggs: "Eggs",
    soy: "Soy",
    priceRange: "Price Range",
    minPrice: "0€",
    maxPrice: "50€",
    applyFilters: "Apply Filters",
    clearFilters: "Clear",
    todayMenu: "Today's Menu",
    starters: "Starters",
    mainCourses: "Main Courses",
    desserts: "Desserts",
    drinks: "Drinks",
    coldDrinks: "Cold Drinks",
    hotDrinks: "Hot Drinks",
    loadingMenu: "Loading menu...",
    ourStory: "Our Story",
    aboutText1: "Apricus was born out of a love for good food and warm hospitality. We offer unique taste experiences in the heart of the city.",
    aboutText2: "We use only the freshest, local ingredients and traditional recipes with a modern twist.",
    freshIngredients: "Fresh Ingredients",
    localIngredients: "Local and seasonal ingredients",
    experiencedChefs: "Experienced Chefs",
    professionalTeam: "Professional kitchen team",
    cozyAtmosphere: "Cozy Atmosphere",
    warmAtmosphere: "Warm and inviting environment",
    cart: "Cart",
    emptyCart: "Your cart is empty",
    addFromMenu: "Add items from the menu",
    total: "Total:",
    checkout: "Checkout",
    favorites: "Favorites",
    noFavorites: "No favorites yet",
    addFavorites: "Add favorites by clicking the heart",
    contactInfo: "Contact Information",
    address: "Address",
    addressValue: "mellunmäki 22, Helsinki",
    phone: "Phone",
    phoneValue: "+358 4056478",
    emailValue: "tk@gmail.com",
    openingHours: "Opening Hours",
    monFri: "Mon-Fri: 10:00 - 22:00",
    sat: "Sat: 11:00 - 23:00",
    sun: "Sun: 12:00 - 21:00",
    footerBrand: "Apricus",
    footerDesc: "Unique taste experiences in the heart of the city",
    footerContact: "Contact Information",
    footerOpeningHours: "Opening Hours",
    quickAccess: "Quick Access",
    copyright: "© 2025 Apricus. All rights reserved.",
    designed: "Designed and built with ❤️",
    showDetails: "Show Details",
    addToCart: "Add to Cart",
    close: "Close",
    directions: "Directions",
    adminMain: "Main Page",
    loadingOrders: "Loading orders..."
  }
};

function updateLanguage(lang) {
  // تحديث العناصر التي تحمل خاصية data-i18n
  document.querySelectorAll('[data-i18n]').forEach(function(el) {
    var key = el.getAttribute('data-i18n');
    if (translations[lang][key]) {
      if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
        el.placeholder = translations[lang][key];
      } else {
        el.textContent = translations[lang][key];
      }
    }
  });
  // دعم العناصر القديمة
  if (document.querySelector('.main-navigation a[href="#etusivu"]'))
    document.querySelector('.main-navigation a[href="#etusivu"]').textContent = translations[lang].home;
  if (document.querySelector('.main-navigation a[href="#menu"]'))
    document.querySelector('.main-navigation a[href="#menu"]').textContent = translations[lang].menu;
  if (document.querySelector('.main-navigation a[href="#tietoa"]'))
    document.querySelector('.main-navigation a[href="#tietoa"]').textContent = translations[lang].info;
  if (document.querySelector('.main-navigation a[href="#yhteystiedot"]'))
    document.querySelector('.main-navigation a[href="#yhteystiedot"]').textContent = translations[lang].contact;
  if (document.getElementById('searchInput'))
    document.getElementById('searchInput').placeholder = translations[lang].searchPlaceholder;
  if (document.querySelector('.brand-text'))
    document.querySelector('.brand-text').textContent = translations[lang].brand;
  if (document.querySelector('label[for="langSelect"]'))
    document.querySelector('label[for="langSelect"]').textContent = translations[lang].language;
  // تحديث القائمة حسب اللغة
  if (typeof renderMenu === 'function') renderMenu();
}

// Event listener for language select
document.addEventListener('DOMContentLoaded', function() {
  const langSelect = document.getElementById('langSelect');
  if (langSelect) {
    langSelect.addEventListener('change', function() {
      updateLanguage(langSelect.value);
    });
    // Set initial language
    updateLanguage(langSelect.value);
  }
});
